M48
; DRILL file {KiCad 8.0.6} date 2025-01-06T00:07:19+0800
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-01-06T00:07:19+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.6
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0327
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0484
%
G90
G05
T1
X6.1415Y-2.8587
X6.1415Y-3.0862
T2
X3.7008Y-3.4961
X6.189Y-4.6063
T3
X3.7008Y-4.6063
X6.189Y-3.4961
M30
